apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/mshatunov/pool-infra-eureka-server:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/mshatunov/pool-infra-eureka-server:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: pool-infra-eureka-server
        chartPath: charts/pool-infra-eureka-server
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/mshatunov/pool-infra-eureka-server"
          image.tag: "{{.DIGEST_HEX}}"
